spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test2?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

#  #스웨거 커스텀 설정
swagger-config:
  title: VueSpringBoard API
  prefix: /api
  url: http://localhost:8080



